//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public System.Guid Bill_Id { get; set; }
        public System.Guid Order_Id { get; set; }
        public double Total { get; set; }
        public Nullable<System.DateTime> Billing_Date { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
