//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Status
    {
        public System.Guid Status_Id { get; set; }
        public System.Guid Order_Id { get; set; }
        public string Order_Status1 { get; set; }
        public Nullable<System.DateTime> Last_Update { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
