//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Processings = new HashSet<Processing>();
        }
    
        public System.Guid Product_Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> Product_Category { get; set; }
        public double Price { get; set; }
        public int Preparation_time { get; set; }
        public string Product_Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Processing> Processings { get; set; }
        public virtual Product_Category Product_Category1 { get; set; }
    }
}
